---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-keycloak-admin
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-keycloak-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-keycloak-admin
