apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# clone and make this single-namespace: see https://github.com/keycloak/keycloak-k8s-resources/issues/6
#  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.1/kubernetes/kubernetes.yml
  - kubernetes.yml
  # RBAC rules to allow the drogue-devbox application to deploy keycloak resources
  - gitops-rbac.yaml