kind: ConfigMap
apiVersion: v1
metadata:
  name: twin-operator-config
  labels:
    app.kubernetes.io/name: twin-operator
    app.kubernetes.io/instance: eclipsecon-2022
    app.kubernetes.io/component: twin-operator
data:
  template.yaml: |
    {{- $.Files.Get "config/template.yaml" | nindent 4}}

  {{ range $path, $_ :=  .Files.Glob  "config/js/*.js" }}
  "js/{{ base $path }}": |
  {{- $.Files.Get $path | nindent 4 }}
  {{ end }}
