apiVersion: apps/v1
kind: Deployment
metadata:
  name: twin-operator
  labels:
    app.kubernetes.io/name: twin-operator
    app.kubernetes.io/instance: eclipsecon-2022
    app.kubernetes.io/component: twin-operator
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind":"ImageStreamTag",
            "name":"twin-operator:latest"
          },
          "fieldPath":"spec.template.spec.containers[?(@.name==\"server\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: twin-operator
      app.kubernetes.io/instance: eclipsecon-2022
      app.kubernetes.io/component: twin-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: twin-operator
        app.kubernetes.io/instance: eclipsecon-2022
        app.kubernetes.io/component: twin-operator
    spec:
      containers:
        - name: server
          image: twin-operator:latest
          env:
            - name: RUST_LOG
              value: info
            - name: RUNTIME__HEALTH__ENABLED
              value: "true"
            - name: RUNTIME__HEALTH__BIND_ADDR
              value: "0.0.0.0:9090"

            - name: OPERATOR__MQTT_URI
              value: ssl://mqtt-integration.sandbox.drogue.cloud:443
            - name: OPERATOR__API
              value: https://api.sandbox.drogue.cloud
            - name: OPERATOR__APPLICATION
              value: eclipsecon-hackathon
            - name: OPERATOR__USER
              value: {{ .Values.drogueCloud.api.user }}
            - name: OPERATOR__TOKEN
              value: {{ .Values.drogueCloud.api.token | quote }}

            - name: TWIN__CONFIGURATION
              value: /etc/twin-operator/config/template.yaml

            - name: TWIN__CLIENT__URL
              value: https://api-eclipsecon-2022.apps.sandbox.drogue.world
            - name: TWIN__CLIENT__ISSUER_URL
              value: https://sso-eclipsecon-2022.apps.sandbox.drogue.world/realms/doppelgaenger

            {{- with .Values.drogueDoppelgaenger.apiSecret }}
            - name: TWIN__CLIENT__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: CLIENT_ID
            - name: TWIN__CLIENT__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: CLIENT_SECRET
            {{- else }}
            - name: TWIN__CLIENT__CLIENT_ID
              value: {{ .Values.drogueDoppelgaenger.api.clientId | quote }}
            - name: TWIN__CLIENT__CLIENT_SECRET
              value: {{ .Values.drogueDoppelgaenger.api.clientSecret | quote }}
            {{- end }}

            - name: TWIN__RECONCILER__APPLICATION
              value: default
            - name: TWIN__RECONCILER__LABEL_SELECTOR__role
              value: node

          ports:
            - containerPort: 9090
              name: health
              protocol: TCP

          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /liveness

          volumeMounts:
            - mountPath: /etc/twin-operator/config
              name: config
              readOnly: true
            - mountPath: /etc/twin-operator/js
              name: config-js
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: twin-operator-config
        - name: config-js
          configMap:
            name: twin-operator-config-js
