kind: Service
apiVersion: v1
metadata:
  name: model-converter
  labels:
    app.kubernetes.io/name: model-converter
    app.kubernetes.io/instance: eclipsecon-2022
    app.kubernetes.io/component: model-converter
spec:
  selector:
    app.kubernetes.io/name: model-converter
    app.kubernetes.io/instance: eclipsecon-2022
    app.kubernetes.io/component: model-converter
  type: ClusterIP
  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
