drogue:
  application:
    name: eclipsecon-hackathon

  integration:
    websocket:
      url: wss://ws-integration.sandbox.drogue.cloud:443

  api:
    user: <yourUserName>
    key: <YourAccessToken>