kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
spec:
  port:
    targetPort: service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: console
