kind: Deployment
apiVersion: apps/v1

metadata:
  name: doppelgaenger-opcua
  labels:
    deployment: doppelgaenger-opcua

spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: doppelgaenger-opcua
  template:
    metadata:
      labels:
        deployment: doppelgaenger-opcua
    spec:
      containers:
        - name: service
          image: ghcr.io/drogue-iot/drogue-doppelgaenger-opcua-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service
            - containerPort: 4840
              name: opcua
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
          env:
            - name: DROGUE_DOPPELGAENGER_OPCUA_SELF_SIGNED_KEY_MODE
              value: ephemeral
            - name: DROGUE_DOPPELGAENGER_API
              value: https://api-eclipsecon-2022.apps.sandbox.drogue.world
            - name: DROGUE_DOPPELGAENGER_APPLICATION
              value: default

            - name: DROGUE_DOPPELGAENGER_OPCUA_ENABLE_ANONYMOUS
              value: {{ .Values.opcua.enableAnonymous | quote }}

            {{- range  $k, $v := .Values.opcua.users }}
            - name: DROGUE_DOPPELGAENGER_OPCUA_USERS_{{ $k | upper }}
              value: {{ $v | quote }}
            {{- end}}

            {{- with .Values.opcua.hostnames }}
            - name: DROGUE_DOPPELGAENGER_OPCUA_HOSTNAMES
              value: {{ . | quote }}
            {{- end }}

            - name: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
              value: {{ .Values.oidc.authServer | quote }}
            - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.clientSecretName }}
                  key: {{ .Values.oidc.clientIdKey }}
            - name: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.clientSecretName }}
                  key: {{ .Values.oidc.clientSecretKey }}
