drogueCloud:
  api:
    # user: <access key user>
    # key: <access key>

oidcAuthServer: https://sso-eclipsecon-2022.apps.sandbox.drogue.world/

database:
  name: eclipsecon
  hostname: postgres
  port: 5432

  username: console
  # password: <password>

  # override the full JDBC url
  # jdbcUrl: jdbc:postgresql://localhost:5432/eclipsecon

postgresql:
  auth:
    username: console # align with database.username
    existingSecret: database
    database: eclipsecon # align with database.name
