---
apiVersion: v1
kind: Namespace
metadata:
  name: eclipsecon-gateway

# ---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mesh-gateway
  namespace: eclipsecon-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mesh-gateway
      app.kubernetes.io/instance: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mesh-gateway
        app.kubernetes.io/instance: gateway
    spec:
      hostNetwork: true
      enableServiceLinks: false
      initContainers:
        - command:
            - bash
            - '-ec'
            - |
              cp -av /etc/meshd-init/config /var/lib/meshd/
              cp -av /etc/meshd-init/lib /var/lib/meshd/
              find /var/lib/meshd/
          image: quay.io/eclipsecon-2022/meshd:0.1.0
          imagePullPolicy: IfNotPresent
          name: init-data
          volumeMounts:
            - mountPath: /var/lib/meshd/config
              name: meshd-config
            - mountPath: /var/lib/meshd/lib
              name: meshd-storage
      containers:
        - name: meshd
          image: quay.io/eclipsecon-2022/meshd:0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /usr/libexec/bluetooth/bluetooth-meshd
            - '--nodetach'
            - '--config'
            - /var/lib/meshd/config
            - '--storage'
            - /var/lib/meshd/lib
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus-socket
            - name: meshd-config
              mountPath: /var/lib/meshd/config
            - name: meshd-storage
              mountPath: /var/lib/meshd/lib
        - name: gateway
          image: quay.io/eclipsecon-2022/gateway:0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - '--drogue-device'
            - gateway4
            - '--drogue-application'
            - eclipsecon-hackathon
            - '--token'
            - dd26596e54e78fa2
          env:
            - name: RUST_LOG
              value: info
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus-socket
      volumes:
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/system_bus_socket
        - name: meshd-config
          emptyDir: {}
        - name: meshd-storage
          emptyDir: {}
