kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: console
spec:
  triggers:
    - type: ImageChange
  source:
    git:
      uri: https://github.com/eclipse-iot/eclipsecon-2022-hackathon/example-apps
    contextDir: console
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: "ubi9-minimal:latest"
  output:
    to:
      kind: ImageStreamTag
      name: console:latest
