[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nrf52833_xxAA"

rustflags = [
  # Code-size optimizations.
  "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
  "-C", "embed-bitcode",
  "-Z", "emit-stack-sizes",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
