[unstable]
#build-std = ["core", "compiler_builtins"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nrf52833_xxAA"

rustflags = [
  # Code-size optimizations.
  "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
  "-C", "embed-bitcode",
  "-Z", "emit-stack-sizes",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"

[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/drogue-iot/btmesh.git"]
git = "https://github.com/drogue-iot/btmesh.git"
branch = "main"
replace-with = "vendored-sources"

[source."https://github.com/drogue-iot/drogue-device.git"]
git = "https://github.com/drogue-iot/drogue-device.git"
rev = "05ef60945cc3736eb7bcba3f2fecb247279fdffa"
replace-with = "vendored-sources"

[source."https://github.com/embassy-rs/embassy.git"]
git = "https://github.com/embassy-rs/embassy.git"
rev = "3b58ac1bf86a2373e479e8e3cf92d2df7c29e00b"
replace-with = "vendored-sources"

[source."https://github.com/embassy-rs/nrf-softdevice.git"]
git = "https://github.com/embassy-rs/nrf-softdevice.git"
rev = "fb9605a108ba45eb022ac9ce7f7be7041efe9523"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
