[package]
name = "eclipsecon-device"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-microbit = { path = "../../embassy-microbit/microbit" }

embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "gpiote", "time-driver-rtc1", "nightly", "unstable-traits"]}
embassy-util = { version = "0.1.0", default-features = false }
embassy-executor = { version = "0.1.0", default-features = false, features = ["time", "defmt-timestamp-uptime", "defmt", "nightly"] }

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-central", "ble-gatt-server", "s140", "nrf52833", "critical-section-impl", "defmt"] }
nrf-softdevice-s140 = { version = "0.1.0" }

btmesh-models = { path = "../../drogue-iot/btmesh/btmesh-models"}
btmesh-device = { path = "../../drogue-iot/btmesh/btmesh-device"}
btmesh-macro = { path = "../../drogue-iot/btmesh/btmesh-macro"}
btmesh-nrf-softdevice = { path = "../../drogue-iot/btmesh/btmesh-nrf-softdevice", features = ["defmt", "nrf52833", "relay", "proxy"] }

heapless = "0.7"
cortex-m-rt = "0.7"

defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }

[patch.crates-io]
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
embassy-util = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }
nrf-softdevice-macro = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }
