[package]
name = "eclipsecon-device"
version = "0.1.0"
edition = "2021"

[dependencies]
btmesh-device = { git = "https://github.com/drogue-iot/btmesh.git", branch = "main" }
btmesh-macro = { git = "https://github.com/drogue-iot/btmesh.git", branch = "main" }

btmesh-common = { git = "https://github.com/drogue-iot/btmesh.git", branch = "main" }
btmesh-models = { git = "https://github.com/drogue-iot/btmesh.git", branch = "main" }
btmesh-nrf-softdevice = { git = "https://github.com/drogue-iot/btmesh.git", branch = "main", default-features = false, features = ["defmt", "nrf52833", "relay"] }
cortex-m-rt = "0.7"

defmt = "0.3"
defmt-rtt = "0.3"
embassy-executor = { version = "0.1.0", default-features = false, features = ["time", "defmt-timestamp-uptime", "defmt", "nightly"] }
embassy-microbit = { git = "https://github.com/lulf/embassy-microbit.git", branch = "main" }

embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "gpiote", "time-driver-rtc1", "nightly", "unstable-traits"] }
embassy-util = { version = "0.1.0", default-features = false }

heapless = "0.7"

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-central", "ble-gatt-server", "s140", "nrf52833", "critical-section-impl"] }
nrf-softdevice-s140 = { version = "0.1.0" }
panic-probe = { version = "0.3", features = ["print-defmt"] }

sensor-model = { path = "../sensor-model", features = ["defmt"] }

[profile.dev]
debug = 2
debug-assertions = true
incremental = false
opt-level = 'z'
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
embassy-util = { git = "https://github.com/embassy-rs/embassy.git", branch = "master" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }
nrf-softdevice-macro = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master" }

[patch."https://github.com/lulf/embassy-microbit.git"]
embassy-microbit = { path = "../../embassy-microbit/microbit" }

[patch."https://github.com/drogue-iot/btmesh.git"]
btmesh-device = { path = "../../drogue-iot/btmesh/btmesh-device" }
btmesh-macro = { path = "../../drogue-iot/btmesh/btmesh-macro" }
btmesh-common = { path = "../../drogue-iot/btmesh/btmesh-common" }
btmesh-models = { path = "../../drogue-iot/btmesh/btmesh-models" }
btmesh-driver = { path = "../../drogue-iot/btmesh/btmesh-driver" }
btmesh-nrf-softdevice = { path = "../../drogue-iot/btmesh/btmesh-nrf-softdevice" }
